### ISSUE TITLE
Permettre d'avoir le dossier fonts ailleurs

### ISSUE THREAD

**Issue by Chouchen** [broncowdd/goofi#1]
Parce que là, grosso modo, on est obligé d'avoir goofi.php dans le dossier parent de fonts ce qu'on ne veut pas forcément si on veut un dossier de police séparé de ces mêmes polices.

Je sais pas si je suis clair.

`$font_folder = 'fonts/';` au départ du script serait pas mal pour factoriser

**Comment by broncowdd** [comment]
oui et en plus c'est pas dur ^^
